services:
  automas:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: automas
    volumes:
      - ./automas_logs:/app/automas_logs:z
      - ./examples/gaia/gaia_logs:/app/examples/gaia/gaia_logs:z
      - ./examples/gaia/gaia_data:/app/examples/gaia/gaia_data:z 
    env_file:
      - .env
    network_mode: "host"
