// Design lifecycle shared by the workspace UI. A generated design may only run
// after it has been generated from the current inputs and explicitly accepted.
export type JudgeMetadata = {
  name: string;
  instructions: string;
  model?: string;
  mcp_tools?: string[];
};

export type DesignMetadata = {
  generated_at?: string;
  pool_model?: string;
  judge_count?: number;
  unused_judges?: string[];
};

export type Design = {
  nodes: string[];
  edges: string[][];
  judge_instructions: Record<string, string>;
  judges?: JudgeMetadata[];
  design_source?: string;
  design_id?: string;
  metadata?: DesignMetadata;
};

export type DesignSource = "generated" | "manual" | "imported";

export type DesignState =
  | "not_generated"
  | "generating"
  | "generated"
  | "failed"
  | "stale";

export type DesignInputs = {
  objective: string;
  taxonomy: string;
  schema: string;
  examples: string;
};

/** Identity of the inputs a design was generated from. */
export function designKey(inputs: DesignInputs, steps: unknown[]): string {
  return JSON.stringify([
    inputs.objective.trim(),
    inputs.taxonomy.trim(),
    inputs.schema.trim(),
    (inputs.examples || "[]").trim(),
    steps,
  ]);
}

/** A generated design goes stale when its inputs change, and recovers if they return. */
export function nextDesignState(
  state: DesignState,
  currentKey: string,
  snapshot: string | null,
): DesignState {
  if (snapshot === null) return state;
  if (currentKey === snapshot) return state === "stale" ? "generated" : state;
  return state === "generated" ? "stale" : state;
}

/** Empty string means the evaluation may run; otherwise the reason it may not. */
export function runBlockedReason(
  source: DesignSource | undefined,
  state: DesignState,
  accepted: boolean,
): string {
  if (source !== "generated") return "";
  if (state === "generating") return "The Meta Agent is still being generated.";
  if (state === "failed")
    return "Meta Agent generation failed. Retry generation before running.";
  if (state === "stale")
    return "Trace, objective, taxonomy, schema, or examples changed after generation. Regenerate the Meta Agent.";
  if (state === "not_generated") return "Run Meta Agent before starting the evaluation.";
  if (!accepted)
    return "Accept the generated pool with “Use this pool” before running.";
  return "";
}

export function designStateLabel(state: DesignState, accepted: boolean): string {
  return {
    not_generated: "Not generated",
    generating: "Generating…",
    generated: accepted ? "Accepted" : "Review required",
    failed: "Generation failed",
    stale: "Stale",
  }[state];
}

export function designSourceHint(source: DesignSource | undefined): string {
  if (source === "generated")
    return "Generated by the meta-agent from the trace, objective, taxonomy, schema, and examples.";
  if (source === "imported")
    return "Imported design. It runs as supplied, without judge generation.";
  return "No judges yet. Run Meta Agent to evaluate this trace.";
}
